export const environment = {
  production: true,
  WIDGET_PLATFORM_API_URL: '||WIDGET_PLATFORM_API_URL_PLACEHOLDER||',
  GRAPHQL_DATA_API_URL: '||GRAPHQL_DATA_API_URL_PLACEHOLDER||',
  FEEDBACK_API_URL: '||FEEDBACK_API_URL_PLACEHOLDER||',
  SUBSCRIBE_API_URL: '||SUBSCRIBE_API_URL_PLACEHOLDER||',
};
